package com.example.line_chrome

import com.example.line_chrome.line.Crypto
import com.example.line_chrome.line.Legy
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * Vectors generated by the Python reference client (`line_chrome.client`) using
 * `cryptography` and `pycryptodome`.
 *
 * Worth pinning because none of this fails loudly at runtime: a wrong shared
 * secret or AAD just produces a message that every other device reports as
 * undecryptable, and a wrong legy MAC gets an empty 200 with no explanation.
 */
class CryptoTest {

    private fun ByteArray.hex() = joinToString("") { "%02x".format(it) }
    private fun String.bytes() = chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    private val privA = ByteArray(32) { it.toByte() }
    private val privB = ByteArray(32) { (it + 100).toByte() }

    @Test
    fun `x25519 derives the public key the reference client does`() {
        val (_, pubA) = Crypto.x25519KeyPair()
        assertEquals(32, pubA.size)   // shape check; the fixed vectors follow

        assertEquals(
            "8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f",
            org.bouncycastle.crypto.params.X25519PrivateKeyParameters(privA, 0)
                .generatePublicKey().encoded.hex()
        )
        assertEquals(
            "7d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2a",
            org.bouncycastle.crypto.params.X25519PrivateKeyParameters(privB, 0)
                .generatePublicKey().encoded.hex()
        )
    }

    @Test
    fun `x25519 shared secret matches and is symmetric`() {
        val pubA = "8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f".bytes()
        val pubB = "7d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2a".bytes()
        val expected = "3ae143fb898911b4591769dc17ca01775cc4cad4d05b8f33a39c79e30fa63a72"

        assertEquals(expected, Crypto.x25519Shared(privA, pubB).hex())
        assertEquals(expected, Crypto.x25519Shared(privB, pubA).hex())
    }

    @Test
    fun `sha256 hashes the concatenation of its arguments`() {
        assertEquals(
            "913387095a01017a1ee385ef1014ad16e72381393c1cc9c6863087469efc4b8e",
            Crypto.sha256("abc".toByteArray(), "def".toByteArray(), "Key".toByteArray()).hex()
        )
    }

    @Test
    fun `xorHalf folds a hash down to 16 bytes`() {
        assertEquals(
            "a4bc986e7f99bbe830fab8a0bc162386",
            Crypto.xorHalf(Crypto.sha256("seed".toByteArray())).hex()
        )
    }

    /** Key ids go into the AAD as signed big-endian i32, negatives included. */
    @Test
    fun `i32be is signed big-endian`() {
        assertEquals("fffffffe", Crypto.i32be(-2).hex())
        assertEquals("12345678", Crypto.i32be(305419896).hex())
    }

    /** The login secret: AES-ECB(SHA256(pincode)) over the raw 32-byte public key. */
    @Test
    fun `aes ecb matches the device-registration secret`() {
        val pubA = "8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f".bytes()
        assertEquals(
            "53525b6153c806da25445d3ce31e4b8f2b1a87ed6db7bcccd675421c56c27ade",
            Crypto.aesEcbEncrypt(Crypto.sha256("202202".toByteArray()), pubA).hex()
        )
    }

    /**
     * A 16-byte GCM nonce, which is what LINE uses and what Conscrypt refuses —
     * the whole reason this goes through BouncyCastle's lightweight API.
     */
    @Test
    fun `aes gcm with a 16-byte nonce and AAD`() {
        val shared = "3ae143fb898911b4591769dc17ca01775cc4cad4d05b8f33a39c79e30fa63a72".bytes()
        val salt = ByteArray(16) { it.toByte() }
        val nonce = ByteArray(16) { (it + 200).toByte() }
        val gcmKey = Crypto.sha256(shared, salt, "Key".toByteArray())
        assertEquals(
            "64c31a997d8a5339c366b3dd351ea8774e44ea26c63b0473845db38cbd19e2f9", gcmKey.hex()
        )

        val aad = "u1111".toByteArray() + "u2222".toByteArray() +
            Crypto.i32be(11) + Crypto.i32be(22) + Crypto.i32be(2) + Crypto.i32be(0)
        val plaintext = """{"text": "hello"}""".toByteArray()

        val ct = Crypto.aesGcmEncrypt(gcmKey, nonce, plaintext, aad)
        assertEquals(
            "5d96e88433a209e4cf431628c671e585ae8d9121c4d30c91087e0254e64a371f0e", ct.hex()
        )
        assertArrayEquals(plaintext, Crypto.aesGcmDecrypt(gcmKey, nonce, ct, aad))
    }

    @Test(expected = Exception::class)
    fun `aes gcm rejects a tampered AAD`() {
        val key = Crypto.sha256("k".toByteArray())
        val nonce = ByteArray(16)
        val ct = Crypto.aesGcmEncrypt(key, nonce, "hi".toByteArray(), "aad".toByteArray())
        Crypto.aesGcmDecrypt(key, nonce, ct, "different".toByteArray())
    }

    @Test
    fun `pkcs7 pads a full block to two`() {
        val padded = Crypto.pkcs7Pad(ByteArray(16))
        assertEquals(32, padded.size)
        assertEquals(16, padded[31].toInt())
        assertEquals(16, Crypto.pkcs7Unpad(padded).size)
    }

    @Test(expected = IllegalArgumentException::class)
    fun `pkcs7 rejects inconsistent padding`() {
        Crypto.pkcs7Unpad(ByteArray(16) { if (it == 15) 4 else 0 })
    }

    /** The full legy body: inner headers, AES-CBC, then the 4-byte xxhash MAC. */
    @Test
    fun `legy encrypts a body without a token`() {
        val aesKey = ByteArray(16) { it.toByte() }
        assertEquals(
            "03d76d86f7570fc4bab7a835e19ad8a1d6c253694a6e17ecdb022c077d604f12a36e2c5499489853651c96c791ffcefd4f49c39b",
            Legy.encrypt(aesKey, "/api/v3p/rs", "010203".bytes() + "body".toByteArray()).hex()
        )
    }

    @Test
    fun `legy carries the auth token as an inner header`() {
        val aesKey = ByteArray(16) { it.toByte() }
        val encrypted = Legy.encrypt(aesKey, "/S4", "payload".toByteArray(), authToken = "tok123")
        assertEquals(
            "274c29c41545ca330639c83400ec6d6ea9dcf07820d1e3110bdb61cc295db7cdd9a31943fc31497678e5d05099cc083412ec3d95",
            encrypted.hex()
        )

        val (headers, body) = Legy.decrypt(aesKey, encrypted)
        assertEquals("/S4", headers["x-lpqs"])
        assertEquals("tok123", headers["x-lt"])
        assertArrayEquals("payload".toByteArray(), body)
    }
}
